using System;

namespace Nls.Base97 {
    namespace EnumResponses {
        public enum TypicalItem : int {
            NonInterview = -5,
            ValidSkip = -4,
            InvalidSkip = -3,
            DoNotKnow = -2,
            Refusal = -1,
        }
        public enum ShareBioparent: int {
            //DoesNotExistInNls = -99,
            NonInterview = -5,
            ValidSkip = -4,
            DoNotKnow = -2,
            Refusal = -1,
            SameBioMom = 18,
            SameBioDad = 19,
        }
        public enum Gender : int {
            InvalidSkip = -3,
            Male = 1,
            Female = 2,
        }
        public enum RaceCohort : byte {
            Black = 1,
            Hispanic = 2,
            Mixed = 3,
            Nbnh = 4, 
        }
        public enum RosterChoice : short {//Int16
            valid_skip = -4,
            self = 0,
            wife = 1,
            husband = 2,
            mother = 3,
            father = 4,
            mother_step = 7,
            father_step = 8,
            mother_adoptive = 5,
            father_adoptive = 6,
            mother_foster = 9,
            father_foster = 10,
            mother_in_law = 11,
            father_in_law = 12,
            sister_full = 13,
            brother_full = 14,
            sister_half_same_mother = 15,
            sister_half_same_father = 16,
            sister_half_unsure = 17,
            brother_half_same_mother = 18,
            brother_half_same_father = 19,
            brother_half_unsure = 20,
            sister_step = 21,
            brother_step = 22,
            sister_adoptive = 23,
            brother_adoptive = 24,
            sister_foster = 25,
            brother_foster = 26,
            brother_in_law = 27,
            sister_in_law = 28,
            grandmother_maternal = 29,
            grandmother_paternal = 30,
            grandmother_social = 31,
            grandmother_unsure = 32,
            grandfather_maternal = 33,
            grandfather_paternal = 34,
            grandfather_social = 35,
            grandfather_unsure = 36,
            great_grandmother = 37,
            great_grandfather = 38,
            great_grandmother_social = 39,
            great_grandmother_unsure = 40,
            great_grandfather_maternal = 41,
            great_grandfather_paternal = 42,
            great_grandfather_social = 43,
            great_grandfather_unsure = 44,
            great_great_grandmother = 45,
            great_great_grandfather = 46,
            granddaughter = 47,
            grandson = 48,
            daughter_bio = 49,
            son_bio = 50,
            daughter_step = 51,
            son_step = 52,
            daughter_adoptive = 53,
            son_adoptive = 54,
            daughter_foster = 55,
            son_foster = 56,
            daughter_of_partner = 57,
            son_of_partner = 58,
            daughter_in_law = 59,
            son_in_law = 60,
            grandmother_in_law = 61,
            grandfather_in_law = 62,
            aunt_in_law = 63,
            uncle_in_law = 64,
            cousin_in_law = 65,
            great_grandmother_in_law = 66,
            great_grandfather_in_law = 67,
            roommate = 68,
            partner = 69,
            aunt_unsure = 70,
            great_aunt = 71,
            uncle_unsure = 72,
            great_uncle = 73,
            niece_unsure = 74,
            niece_step = 75,
            niece_foster = 76,
            niece_adoptive = 77,
            nephew_unsure = 78,
            nephew_step = 79,
            nephew_foster = 80,
            nephew_adoptive = 81,
            cousin_female_unsure = 82,
            cousin_male_unsure = 83,
            relative_other = 84,
            nonrelative_other = 85,
            great_grandson = 86,
            great_granddaughter = 87,
            relationship_missing = 99,
        }
    }
}
//public enum MultipleBirthType : int {//'These values come from NLS Gen1 items such as R48260.00 and R81067.00
//   NonInterview = -5,
//   ValidSkip = -4,
//   DoNotKnow = -2,
//   Refusal = -1,
//   Identical = 1,
//   Fraternal = 2,
//}}
